### ISSUE TITLE
Did not see org.picketlink.identity.federation.bindings.tomcat.sp.ServiceProviderAuthenticator

### ISSUE THREAD

**Issue by mksmanjit** [Leyart/picketlink-tomcat8-common#1]
Hi,

I did not find org.picketlink.identity.federation.bindings.tomcat.sp.ServiceProviderAuthenticator and when i see some files are missing in your project as compare the to the picket link latest jar.

Can you please suggest from where i get those files

**Comment by Leyart** [comment]
Hello,

All the remaining files can be found in

https://github.com/Leyart/picketlink-tomcat8

These ones are just the common ones.
Please let me know if with this library you have solved the issue.

**Comment by mksmanjit** [comment]
Thanks, it worked for me.
I wanted to upgrade picket link to tomcat 8,5.23 but i am getting compilation error org.apache.catalina.util.LifecycleSupport.

LifecycleSupport is removed from the 8.5.23, do you have any idea that is there are any class which we can use instead of LifecycleSupport.

**Comment by Leyart** [comment]
There have been significant changes from 8.0.x to 8.5.x reported here:

https://tomcat.apache.org/migration-85.html

This repo has libraries for Tomcat 8.0.x, possibly in the future I will do a porting for 8.5.x but no ETA whatsoever. You can try to use this as a starting point for a porting yourself.
Good luck ;)

**Comment by mksmanjit** [comment]
ok.

Now i am using picketlink with tomcat 8 and i followed the step given in the https://dzone.com/articles/saml-single-sign-on-with-tomcat-and-picketlink but when i hitting my webapplication URL it is not redirecting to the Okata server(setup as a developer account).

And how we are defining roles, do we need to define it in the picketlink.xml?

Please help..
