### ISSUE TITLE
Can't use it with picketlink-tomcat7-single

### ISSUE THREAD

**Issue by ribeirocn** [Leyart/picketlink-tomcat8-common#4]
Alert, maybe a newbie question.

When I try to compile picketlink-tomcat7-single with the abstract classes provided in picketlink-tomcat8-common I get several errors, because picketlink-tomcat7-single is using catalina 7 libs. If I use catalina 8 libs with picketlink-tomcat7-single I get another set of errors. So it seems that I need a picketlink-tomcat8-single, but I could not find it. What am I missing?

**Comment by Leyart** [comment]
You are missing this:

https://github.com/Leyart/picketlink-tomcat8

Let me know if it helps :)

**Comment by ribeirocn** [comment]
Right on spot :-). Sorry, I'm not sure how did I miss it.
